#ifndef _CHEESOS2_INTERRUPT_EXCEPTIONS_H
#define _CHEESOS2_INTERRUPT_EXCEPTIONS_H

enum idt_exception {
    IDT_EXCEPTION_DIVIDE_ERROR = 0,
    IDT_EXCEPTION_DEBUG = 1,
    IDT_EXCEPTION_NMI = 2,
    IDT_EXCEPTION_BREAKPOINT = 3,
    IDT_EXCEPTION_OVERFLOW = 4,
    IDT_EXCEPTION_BOUND_RANGE = 5,
    IDT_EXCEPTION_INVALID_OPCODE = 6,
    IDT_EXCEPTION_DEVICE_NOT_AVAILABLE = 7,
    IDT_EXCEPTION_DOUBLE_FAULT = 8,
    IDT_EXCEPTION_COPROC_SEGMENT_OVR = 9,
    IDT_EXCEPTION_INVALID_TSS = 10,
    IDT_EXCEPTION_SEGMENT_NOT_PRESENT = 11,
    IDT_EXCEPTION_STACK_SEGMENT_FAULT = 12,
    IDT_EXCEPTION_GENERAL_PROTECTION_FAULT = 13,
    IDT_EXCEPTION_PAGE_FAULT = 14,
    IDT_EXCEPTION_RESERVED_15 = 15,
    IDT_EXCEPTION_X87 = 16,
    IDT_EXCEPTION_ALIGNMENT = 17,
    IDT_EXCEPTION_MACHINE_CHECK = 18,
    IDT_EXCEPTION_SIMD = 19,
    IDT_EXCEPTION_VIRTUALIZATION = 20,
    IDT_EXCEPTION_CONTROL_PROTECTION = 21,
};

void idt_exceptions_load(void);

#endif
